# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('android', '안드로이드 앱'), ('ios', '아이폰 앱'), ('web', '웹')], default='android', max_length=10)),
                ('content_txt', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Introduce',
        ),
        migrations.AddField(
            model_name='comment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Work'),
        ),
    ]
