# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20161230_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('rec', '승인'), ('un', '미승인')], default='un', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_comment', to='about.Work'),
        ),
    ]
