# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20170107_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='strapline',
            field=models.CharField(default='', max_length=50),
        ),
    ]
