# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_work_strapline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='strapline',
            field=models.CharField(max_length=50),
        ),
    ]
