# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20170107_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='author',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='strapline',
            new_name='enterprise',
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
