# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20170107_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
